#! /bin/bash
# *************************************************************
# *************************************************************
# Author : HTMLDigger
# Date : Sunday 14 February 2021 07:14:17 PM IST
# Script Name : 
# Version : v1.0
# *************************************************************
# *************************************************************

date
echo "uptime:"
uptime
echo "Currently connected:"
w
echo "--------------------"
echo "Last logins:"
last -a | head -3
echo "--------------------"
echo "Disk and memory usage:"
df -h | xargs | awk '{print "Free/total disk: " $11 " / " $9}'
free -m | xargs | awk '{print "Free/total memory: " $17 " / " $8 " MB"}'
echo "--------------------"

